/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:3e245dc1-0726-43d7-bf57-edc0753d535a",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_NLUb262IM",
    "aws_user_pools_web_client_id": "6il5ndf73ps99suivfuplvare",
    "oauth": {
        "domain": "another-to-do-local.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
